//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UBLXsl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UBLXsl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UBLXsl", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;xsl:stylesheet doc:dummy-for-xmlns=&quot;&quot; cac:dummy-for-xmlns=&quot;&quot; cbc:dummy-for-xmlns=&quot;&quot; ccts:dummy-for-xmlns=&quot;&quot; sdt:dummy-for-xmlns=&quot;&quot; udt:dummy-for-xmlns=&quot;&quot; xs:dummy-for-xmlns=&quot;&quot; version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:sch=&quot;http://www.ascc.net/xml/schematron&quot; xmlns:iso=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:doc=&quot;urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2&quot; xmlns:cac=&quot;urn:oasis:names:specificatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OIOUBL_ApplicationResponse_Schematron {
            get {
                return ResourceManager.GetString("OIOUBL_ApplicationResponse_Schematron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;xsl:stylesheet doc:dummy-for-xmlns=&quot;&quot; cac:dummy-for-xmlns=&quot;&quot; cbc:dummy-for-xmlns=&quot;&quot; ccts:dummy-for-xmlns=&quot;&quot; sdt:dummy-for-xmlns=&quot;&quot; udt:dummy-for-xmlns=&quot;&quot; xs:dummy-for-xmlns=&quot;&quot; version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:sch=&quot;http://www.ascc.net/xml/schematron&quot; xmlns:iso=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:doc=&quot;urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2&quot; xmlns:cac=&quot;urn:oasis:names:specification:ubl:sch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OIOUBL_CreditNote_Schematron {
            get {
                return ResourceManager.GetString("OIOUBL_CreditNote_Schematron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;xsl:stylesheet doc:dummy-for-xmlns=&quot;&quot; cac:dummy-for-xmlns=&quot;&quot; cbc:dummy-for-xmlns=&quot;&quot; ccts:dummy-for-xmlns=&quot;&quot; sdt:dummy-for-xmlns=&quot;&quot; udt:dummy-for-xmlns=&quot;&quot; xs:dummy-for-xmlns=&quot;&quot; version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:sch=&quot;http://www.ascc.net/xml/schematron&quot; xmlns:iso=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:doc=&quot;urn:oasis:names:specification:ubl:schema:xsd:Invoice-2&quot; xmlns:cac=&quot;urn:oasis:names:specification:ubl:schema [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OIOUBL_Invoice_Schematron {
            get {
                return ResourceManager.GetString("OIOUBL_Invoice_Schematron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;xsl:stylesheet doc:dummy-for-xmlns=&quot;&quot; cac:dummy-for-xmlns=&quot;&quot; cbc:dummy-for-xmlns=&quot;&quot; ccts:dummy-for-xmlns=&quot;&quot; sdt:dummy-for-xmlns=&quot;&quot; udt:dummy-for-xmlns=&quot;&quot; xs:dummy-for-xmlns=&quot;&quot; version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:sch=&quot;http://www.ascc.net/xml/schematron&quot; xmlns:iso=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:doc=&quot;urn:oasis:names:specification:ubl:schema:xsd:Order-2&quot; xmlns:cac=&quot;urn:oasis:names:specification:ubl:schema:x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OIOUBL_Order_Schematron {
            get {
                return ResourceManager.GetString("OIOUBL_Order_Schematron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;xsl:stylesheet doc:dummy-for-xmlns=&quot;&quot; cac:dummy-for-xmlns=&quot;&quot; cbc:dummy-for-xmlns=&quot;&quot; ccts:dummy-for-xmlns=&quot;&quot; sdt:dummy-for-xmlns=&quot;&quot; udt:dummy-for-xmlns=&quot;&quot; xs:dummy-for-xmlns=&quot;&quot; version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:sch=&quot;http://www.ascc.net/xml/schematron&quot; xmlns:iso=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:doc=&quot;urn:oasis:names:specification:ubl:schema:xsd:Reminder-2&quot; xmlns:cac=&quot;urn:oasis:names:specification:ubl:schem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OIOUBL_Reminder_Schematron {
            get {
                return ResourceManager.GetString("OIOUBL_Reminder_Schematron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;xsl:stylesheet doc:dummy-for-xmlns=&quot;&quot; cac:dummy-for-xmlns=&quot;&quot; cbc:dummy-for-xmlns=&quot;&quot; ccts:dummy-for-xmlns=&quot;&quot; sdt:dummy-for-xmlns=&quot;&quot; udt:dummy-for-xmlns=&quot;&quot; xs:dummy-for-xmlns=&quot;&quot; version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:sch=&quot;http://www.ascc.net/xml/schematron&quot; xmlns:iso=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:doc=&quot;urn:oioubl:names:specification:oioubl:schema:xsd:UtilityStatement-2&quot; xmlns:cac=&quot;urn:oioubl:names:specificat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OIOUBL_UtilityStatement_Schematron {
            get {
                return ResourceManager.GetString("OIOUBL_UtilityStatement_Schematron", resourceCulture);
            }
        }
    }
}
